"""Link cherry-picking: automate the link selection both implementations did by hand.

Both implementations ended up with the same 8 sublinks, chosen by eye. implementation_1's
code contains the pieces of a systematic procedure (``check_link_contact_loss``,
``rain_detection`` / ``roc_threshold``, ``filter_links_by_accumulation``, ``keep_links``)
and implementation_2 keeps exactly one sublink per link (``sublink_choice``). This module
chains those steps into a reproducible pipeline:

====  ============================  ==========================================================
 0    metadata                      frequency 10-100 GHz, path 0.3-20 km, coordinates in NYC
                                    (``cml.qc``); duplicates are *not* dropped here (stage 4)
 1    contact loss                  implementation_1 ``check_link_contact_loss``: reject if more
                                    than 40 % of the minutes with gauge rain are missing
 2    rain response                 implementation_1 ``rain_detection`` + ``roc_threshold``:
                                    rolling-sigma wet/dry vs the gauge reference at 15 min;
                                    per-link threshold by the ROC rule (TPR >= 0.8, closest to
                                    (0, 1)); keep if skill TPR - FPR >= 0.3 **and** the 15-min
                                    rain correlates with the gauges (r >= 0.3) - the automated
                                    form of the visual attenuation screening
 3    accumulation                  implementation_1 ``filter_links_by_accumulation``: total
                                    rain (implementation_1's dynamic-baseline estimator) within
                                    ``tol`` (40 %) of the gauges within 5 km, else of the median
                                    gauge
 4    one sublink per path          implementation_1 ``keep_links`` / implementation_2
                                    ``sublink_choice``: among sublinks on the same path (either
                                    direction) keep the one that correlates best with the gauges
====  ============================  ==========================================================

**Reference = PWS gauges only, on calibration events.** Selection never looks at the radar,
and by default it is calibrated on the rain events of the OpenMesh record that are *not* in the
evaluation catalog, so scores against MRMS on the catalog events are out-of-sample.
"""

from __future__ import annotations

import json
import logging
from dataclasses import asdict, dataclass, field
from pathlib import Path

import numpy as np
import pandas as pd
import xarray as xr

from core.geo import haversine_m
from core.opensense import openmesh as om
from . import baseline as bl
from .estimators import DynamicBaseline
from .link_qc import QCConfig, metadata_qc

log = logging.getLogger(__name__)


@dataclass
class SelectionConfig:
    qc: QCConfig = field(default_factory=QCConfig)
    gauge_radius_m: float = 5000.0        # implementation_1: gauges within 5 km of the midpoint
    min_gauges: int = 1
    rain_rate_mm_h: float = 0.5           # implementation_1 check_link_contact_loss
    max_nan_in_rain: float = 0.40         # implementation_1 check_link_contact_loss
    wet_mm_h: float = 0.1                 # gauge reference "wet" at 15 min
    wd_window: int = 60                   # rolling-sigma window (min)
    wd_thresholds: tuple = tuple(np.round(np.arange(0.05, 1.51, 0.05), 2))
    min_tpr: float = 0.8                  # implementation_1 roc_threshold
    min_skill: float = 0.3                # TPR - FPR (Peirce skill score)
    min_corr: float = 0.3
    accumulation_tol: float = 0.4         # implementation_1 filter_links_by_accumulation
    path_tolerance_m: float = 100.0
    spinup: str = "6h"


@dataclass
class SelectionResult:
    selected: list
    table: pd.DataFrame
    calibration_events: list
    config: dict

    def save(self, folder: str | Path) -> Path:
        folder = Path(folder)
        folder.mkdir(parents=True, exist_ok=True)
        self.table.round(4).to_csv(folder / "link_selection_table.csv")
        (folder / "selected_links.json").write_text(json.dumps(
            {"selected": self.selected, "calibration_events": self.calibration_events,
             "config": self.config}, indent=2, default=str))
        (folder / "README.md").write_text(self.markdown())
        return folder / "selected_links.json"

    def markdown(self) -> str:
        """Human-readable summary: stages, counts, and every non-metadata candidate."""
        s = self.summary()
        c = self.config
        L = ["# Link selection (cherry-picking)", "",
             "Generated by `python src/run.py select` (`nyc_rain_maps.link_selection`). Reference: PWS gauges "
             f"within {c['gauge_radius_m'] / 1000:g} km of each link midpoint, on "
             f"{len(self.calibration_events)} calibration rain events that are not in the evaluation "
             "catalog. The radar is never used.", "",
             f"**Selected ({len(self.selected)}):** " + ", ".join(f"`{x}`" for x in self.selected), "",
             "| stage | criterion (from the original code) | rejected |", "|---|---|---|",
             f"| 0 metadata | {c['qc']['min_frequency_ghz']:g}-{c['qc']['max_frequency_ghz']:g} GHz, "
             f"{c['qc']['min_length_km']:g}-{c['qc']['max_length_km']:g} km, inside NYC | "
             f"{s['rejected_by_stage'].get('0 metadata', 0)} |",
             f"| 1 contact loss | <= {c['max_nan_in_rain']:.0%} missing while gauges > {c['rain_rate_mm_h']:g} "
             "mm/h (impl. 1 `check_link_contact_loss`) | "
             f"{s['rejected_by_stage'].get('1 contact loss', 0)} |",
             f"| 2 rain response | rolling-sigma wet/dry skill TPR-FPR >= {c['min_skill']:g} (ROC threshold, "
             f"TPR >= {c['min_tpr']:g}) and r >= {c['min_corr']:g} with gauges (impl. 1 `rain_detection`, "
             f"`roc_threshold`) | {s['rejected_by_stage'].get('2 rain response', 0)} |",
             f"| 3 accumulation | link total within {c['accumulation_tol']:.0%} of nearby gauges or of the "
             "median gauge (impl. 1 `filter_links_by_accumulation`) | "
             f"{s['rejected_by_stage'].get('3 accumulation', 0)} |",
             "| 4 one per path | best gauge correlation among sublinks on the same path, either "
             "direction (impl. 1 `keep_links`, impl. 2 `sublink_choice`) | "
             f"{s['rejected_by_stage'].get('4 one per path', 0)} |", "",
             "## Candidates past the metadata stage", "",
             "| sublink | GHz | km | gauges | missing in rain | skill | r | link/gauge total | result |",
             "|---|---|---|---|---|---|---|---|---|"]
        t = self.table[~self.table.stage_failed.fillna("").str.startswith("0")]
        for lk, r in t.iterrows():
            res = "**selected**" if bool(r.selected) else str(r.stage_failed)
            L.append(f"| `{lk}` | {r.frequency:.1f} | {r.length:.2f} | {int(r.n_gauges)} | "
                     f"{r.nan_in_rain:.0%} | {r.skill:.2f} | {r['corr']:.2f} | {r.accumulation_ratio:.2f} | {res} |")
        L += ["", "Files: `selected_links.json` (list, calibration events, configuration), "
              "`link_selection_table.csv` (all 103 sublinks with every statistic).", ""]
        return "\n".join(L)

    @classmethod
    def load(cls, folder: str | Path) -> "SelectionResult":
        folder = Path(folder)
        meta = json.loads((folder / "selected_links.json").read_text())
        table = pd.read_csv(folder / "link_selection_table.csv", index_col=0)
        return cls(meta["selected"], table, meta["calibration_events"], meta["config"])

    def summary(self) -> dict:
        t = self.table
        return {"candidates": len(t),
                "rejected_by_stage": t.loc[~t.selected.astype(bool), "stage_failed"]
                .str.split(":").str[0].value_counts().sort_index().to_dict(),
                "selected": len(self.selected)}


# ------------------------------------------------------------------ helpers


def gauge_reference_15min(links: xr.Dataset, pws: xr.Dataset, radius_m: float
                          ) -> tuple[xr.DataArray, np.ndarray]:
    """Mean rain rate (mm/h) of the PWS within ``radius_m`` of each link, 15-min bins.

    Bins are interval-ENDING. Returns ``(ref(link, time15), n_gauges per link)``; links
    without a gauge in range get NaN.
    """
    rain15 = pws["rain"].resample(time="15min", label="right", closed="right").sum(min_count=1) * 4
    out, n = [], []
    for lat, lon in zip(links.mid_lat.values, links.mid_lon.values):
        d = haversine_m(lat, lon, pws.lat.values, pws.lon.values)
        idx = np.flatnonzero(d <= radius_m)
        n.append(idx.size)
        out.append(rain15.isel(station=idx).mean("station", skipna=True).values if idx.size
                   else np.full(rain15.sizes["time"], np.nan))
    ref = xr.DataArray(np.array(out), dims=("link", "time"),
                       coords={"link": links.link.values, "time": rain15.time.values})
    return ref, np.array(n)


def _to15(x: xr.DataArray, how: str) -> xr.DataArray:
    r = x.resample(time="15min", label="right", closed="right")
    return getattr(r, how)()


def _paths(table: pd.DataFrame, tol_m: float) -> pd.Series:
    """Path id per sublink: same cml_id, or endpoints within ``tol_m`` in either direction."""
    ids, reps = {}, []
    for lk, r in table.iterrows():
        pid = None
        for rep_lk, rep in reps:
            same = (haversine_m(r.site_0_lat, r.site_0_lon, rep.site_0_lat, rep.site_0_lon) < tol_m and
                    haversine_m(r.site_1_lat, r.site_1_lon, rep.site_1_lat, rep.site_1_lon) < tol_m)
            flip = (haversine_m(r.site_0_lat, r.site_0_lon, rep.site_1_lat, rep.site_1_lon) < tol_m and
                    haversine_m(r.site_1_lat, r.site_1_lon, rep.site_0_lat, rep.site_0_lon) < tol_m)
            if r.cml_id == rep.cml_id or same or flip:
                pid = ids[rep_lk]
                break
        if pid is None:
            pid = f"path{len(reps):02d}"
            reps.append((lk, r))
        ids[lk] = pid
    return pd.Series(ids, name="path")


def calibration_events(min_total_mm: float = 5.0, exclude_selected: bool = True) -> pd.DataFrame:
    """Rain events of the OpenMesh record for calibration (catalog evaluation events excluded)."""
    from .settings import repo_events_dir
    df = pd.read_csv(repo_events_dir() / "all_detected_events.csv")
    df = df[df.in_openmesh.astype(bool) & (df.ptype == "rain") & (df.total_mm >= min_total_mm)]
    if exclude_selected:
        df = df[~df.selected.astype(bool)]
    return df[["event_id", "start", "end", "total_mm"]].reset_index(drop=True)


# -------------------------------------------------------------------- main


def select_links(events: pd.DataFrame | None = None, config: SelectionConfig | None = None
                 ) -> SelectionResult:
    """Run stages 0-4 over ``events`` (default: :func:`calibration_events`)."""
    cfg = config or SelectionConfig()
    events = calibration_events() if events is None else events
    table = om.sublinks_table()

    kept0, log0 = metadata_qc(table, _no_duplicates(cfg.qc))
    t = table.copy()
    t["stage_failed"] = ""
    t.loc[log0.link.values, "stage_failed"] = "0 metadata: " + log0.reason.values
    cand = [lk for lk in t.index if lk in kept0]
    log.info("selection: %d candidates after metadata QC, %d calibration events", len(cand), len(events))

    thr = np.array(cfg.wd_thresholds)
    stats = {lk: {"rain_minutes": 0, "nan_in_rain": 0, "sum_link": 0.0, "sum_gauge": 0.0,
                  "tp": np.zeros(thr.size), "fp": np.zeros(thr.size), "fn": np.zeros(thr.size),
                  "tn": np.zeros(thr.size), "x": [], "y": [], "n_gauges": 0, "sum_median": 0.0}
             for lk in cand}
    est = DynamicBaseline(gap_fill="gauge_q99", nan_to_zero=True)

    for ev in events.itertuples():
        t0, t1 = pd.Timestamp(ev.start), pd.Timestamp(ev.end)
        links = om.load_links(t0 - pd.Timedelta(cfg.spinup), t1, cand)
        pws = om.load_pws(t0 - pd.Timedelta(cfg.spinup) - pd.Timedelta("1h"), t1)
        ref, n_g = gauge_reference_15min(links, pws, cfg.gauge_radius_m)
        ref = ref.sel(time=slice(t0 + pd.Timedelta("15min"), t1))
        # network median gauge total (implementation_1's fallback reference)
        median_total = float(pws["rain"].sel(time=slice(t0 + pd.Timedelta("5min"), t1))
                             .sum("time", min_count=1).median())
        rain = est.estimate(links, pws=pws)["rain"]
        rain15 = _to15(rain, "mean").sel(time=ref.time)
        rsl = links["rsl"].sel(time=slice(t0 + pd.Timedelta("1min"), t1))
        nan15 = _to15(rsl.isnull().astype(float), "sum").sel(time=ref.time)
        att = (-links["rsl"]).values
        for i, lk in enumerate(cand):
            s = stats[lk]
            s["n_gauges"] = max(s["n_gauges"], int(n_g[i]))
            g = ref.values[i]
            if not np.isfinite(g).any():
                continue
            raining = g > cfg.rain_rate_mm_h
            s["rain_minutes"] += int(raining.sum()) * 15
            s["nan_in_rain"] += float(nan15.values[i][raining].sum())
            r = rain15.values[i]
            ok = np.isfinite(g) & np.isfinite(r)
            s["sum_link"] += float(r[ok].sum() / 4)
            s["sum_gauge"] += float(g[ok].sum() / 4)
            s["sum_median"] += median_total if np.isfinite(median_total) else 0.0
            s["x"].append(r[ok])
            s["y"].append(g[ok])
            gw = g >= cfg.wet_mm_h
            if np.isnan(att[i]).all():
                continue
            a = np.nan_to_num(att[i], nan=np.nanmedian(att[i]))
            _, sig = bl.std_wet_dry(a[None], cfg.wd_window, 1.0)
            sig = xr.DataArray(sig[0], dims="time", coords={"time": links.time.values})
            sig15 = _to15(sig, "max").sel(time=ref.time).values
            for k, th in enumerate(thr):
                lw = sig15 > th
                s["tp"][k] += np.sum(lw & gw & ok)
                s["fp"][k] += np.sum(lw & ~gw & ok)
                s["fn"][k] += np.sum(~lw & gw & ok)
                s["tn"][k] += np.sum(~lw & ~gw & ok)

    rows = {}
    for lk, s in stats.items():
        tpr = s["tp"] / np.maximum(s["tp"] + s["fn"], 1)
        fpr = s["fp"] / np.maximum(s["fp"] + s["tn"], 1)
        dist = np.sqrt(fpr ** 2 + (1 - tpr) ** 2)
        k = int(np.nanargmin(np.where(tpr >= cfg.min_tpr, dist, np.nan))) if (tpr >= cfg.min_tpr).any() \
            else int(np.nanargmin(dist))
        x = np.concatenate(s["x"]) if s["x"] else np.array([])
        y = np.concatenate(s["y"]) if s["y"] else np.array([])
        corr = float(np.corrcoef(x, y)[0, 1]) if x.size > 10 and x.std() > 0 and y.std() > 0 else np.nan
        rows[lk] = {"n_gauges": s["n_gauges"], "rain_minutes": s["rain_minutes"],
                    "nan_in_rain": s["nan_in_rain"] / s["rain_minutes"] if s["rain_minutes"] else np.nan,
                    "wd_threshold_db": float(thr[k]), "tpr": float(tpr[k]), "fpr": float(fpr[k]),
                    "skill": float(tpr[k] - fpr[k]), "corr": corr,
                    "link_total_mm": s["sum_link"], "gauge_total_mm": s["sum_gauge"],
                    "accumulation_ratio": s["sum_link"] / s["sum_gauge"] if s["sum_gauge"] > 0 else np.nan,
                    "median_gauge_ratio": s["sum_link"] / s["sum_median"] if s["sum_median"] > 0 else np.nan}
    m = pd.DataFrame.from_dict(rows, orient="index")
    t = t.join(m)

    for lk in cand:
        r = t.loc[lk]
        if r.n_gauges < cfg.min_gauges:
            t.loc[lk, "stage_failed"] = "1 contact loss: no gauge within radius"
        elif not (r.nan_in_rain <= cfg.max_nan_in_rain):
            t.loc[lk, "stage_failed"] = f"1 contact loss: {r.nan_in_rain:.0%} missing during rain"
        elif not (r["skill"] >= cfg.min_skill and r["corr"] >= cfg.min_corr):
            t.loc[lk, "stage_failed"] = f"2 rain response: skill {r['skill']:.2f}, r {r['corr']:.2f}"
        elif not (abs(r.accumulation_ratio - 1) <= cfg.accumulation_tol
                  or abs(r.median_gauge_ratio - 1) <= cfg.accumulation_tol):
            t.loc[lk, "stage_failed"] = (f"3 accumulation: link/nearby gauges {r.accumulation_ratio:.2f}, "
                                         f"link/median gauge {r.median_gauge_ratio:.2f}")

    ok = t.index[(t.stage_failed == "") & t.index.isin(cand)]
    paths = _paths(t.loc[ok], cfg.path_tolerance_m) if len(ok) else pd.Series(dtype=str)
    t["path"] = paths
    selected = []
    for pid, members in paths.groupby(paths):
        best = t.loc[members.index].sort_values(["corr", "skill"], ascending=False).index[0]
        selected.append(best)
        for lk in members.index:
            if lk != best:
                t.loc[lk, "stage_failed"] = f"4 one per path: same path as {best}, lower gauge correlation"
    t["selected"] = t.index.isin(selected)
    selected = [lk for lk in t.index if lk in selected]
    return SelectionResult(selected, t, list(events.event_id if "event_id" in events else events.index),
                           {k: (v if not isinstance(v, QCConfig) else _qc_dict(v))
                            for k, v in asdict(cfg).items()})


def _no_duplicates(qc: QCConfig) -> QCConfig:
    """QC config whose duplicate stage never fires (paths are resolved in stage 4)."""
    return QCConfig(**{**asdict(qc), "domain": qc.domain, "duplicate_tolerance_m": -1.0})


def _qc_dict(qc: QCConfig) -> dict:
    d = asdict(qc)
    d["domain"] = asdict(qc.domain) if not isinstance(d["domain"], dict) else d["domain"]
    return d


def default_selection_dir() -> Path:
    from .settings import repo_reports_dir
    return repo_reports_dir() / "link_selection"


def load_or_select(folder: str | Path | None = None) -> SelectionResult:
    """The saved selection (``results/link_selection``), computing it on first use."""
    folder = Path(folder) if folder else default_selection_dir()
    if (folder / "selected_links.json").exists():
        return SelectionResult.load(folder)
    res = select_links()
    res.save(folder)
    return res


__all__ = ["SelectionConfig", "SelectionResult", "select_links", "load_or_select",
           "calibration_events", "gauge_reference_15min"]
