"""``results/report.md`` from a :class:`~multisensor_maps.study.Study` - numbers, not prose."""

from __future__ import annotations

import pandas as pd

from .plots import NAMES
from .settings import CHECK_POINTS, RESULTS_DIR

GAUGES = {"pws", "city", "gauges"}
CHECK_NAMES = {"city": "municipal", "pws": "PWS", "gauges": "ARPAE"}


def _fmt_table(df: pd.DataFrame, cols: list, pct: tuple = ("rel_bias", "coverage")) -> list:
    head = "| " + " | ".join(cols) + " |"
    lines = [head, "|" + "---|" * len(cols)]
    for r in df.itertuples():
        cells = []
        for c in cols:
            v = getattr(r, c)
            if c in pct:
                cells.append(f"{v:+.0%}" if c == "rel_bias" else f"{v:.0%}")
            elif isinstance(v, float):
                cells.append(f"{v:.2f}")
            else:
                cells.append(str(v))
        lines.append("| " + " | ".join(cells) + " |")
    return lines


def findings(study) -> list:
    """Plain-language findings derived from the pooled tables."""
    out = []
    pm, pp = study.pooled_maps, study.pooled_points
    for n in NAMES:
        m = pm[(pm.network == n) & (pm.reference == "radar") & (pm.cells != "all")]
        if m.empty:
            continue
        g = m[m.estimate.isin(GAUGES)].sort_values("nrmse")
        c = m[~m.estimate.isin(GAUGES) & (m.coverage >= 0.9)].sort_values("nrmse")
        # gauges within 5 km of a link: the ones a link map can reach
        p = pp[(pp.network == n) & (pp.subset == "gauges <= 5 km of a link")]
        loo = p[p.estimate.str.contains("leave-one-out")]
        rad = p[p.estimate == "radar"]
        pc = p[~p.estimate.isin(GAUGES) & ~p.estimate.str.contains("leave-one-out") & (p.estimate != "radar")
               & (p.coverage >= 0.8)].sort_values("nrmse")
        txt = f"**{NAMES[n]}.** Near the links, "
        if len(g):
            txt += (f"the {g.estimate.iloc[0]} map differs from the radar by NRMSE {g.nrmse.iloc[0]:.2f} "
                    f"(bias {g.rel_bias.iloc[0]:+.0%}); ")
        if len(c):
            txt += (f"the best link map (`{c.estimate.iloc[0]}`) by {c.nrmse.iloc[0]:.2f} "
                    f"({c.rel_bias.iloc[0]:+.0%}), the worst (`{c.estimate.iloc[-1]}`) by {c.nrmse.iloc[-1]:.2f}. ")
        if len(loo) and len(rad) and len(pc):
            txt += (f"At the {CHECK_NAMES[CHECK_POINTS[n]]} gauges within 5 km of a link: radar "
                    f"{rad.nrmse.iloc[0]:.2f}, the other gauges {loo.nrmse.iloc[0]:.2f}, the best link map "
                    f"`{pc.estimate.iloc[0]}` {pc.nrmse.iloc[0]:.2f}.")
        out.append(txt)
    return out


def grid_tables(study) -> list:
    """Retrieval x interpolation: NRMSE against the radar near links, and at the gauges."""
    L = []
    pm, pp = study.pooled_maps, study.pooled_points
    for n in NAMES:
        m = pm[(pm.network == n) & (pm.reference == "radar") & (pm.cells != "all")
               & pm.estimate.str.contains(" ")].copy()
        if m.empty:
            continue
        m[["retrieval", "interpolation"]] = m.estimate.str.split(" ", n=1, expand=True)
        p = pp[(pp.network == n) & (pp.subset == "gauges <= 5 km of a link") & pp.estimate.str.contains(" ")
               & ~pp.estimate.str.contains("leave-one-out")].copy()
        p[["retrieval", "interpolation"]] = p.estimate.str.split(" ", n=1, expand=True)
        for label, t in (("against the radar, cells <= 2 km of a link", m),
                         (f"at the {CHECK_NAMES[CHECK_POINTS[n]]} gauges <= 5 km of a link", p)):
            if t.empty:
                continue
            piv = t.pivot_table(index="retrieval", columns="interpolation", values="nrmse")
            piv = piv[[c for c in ("idw", "line", "gmz") if c in piv]].sort_values(piv.columns[0])
            L += [f"**{NAMES[n]}, hourly NRMSE {label}:**", "",
                  "| retrieval | " + " | ".join(piv.columns) + " |", "|---|" + "---|" * len(piv.columns)]
            for r, row in piv.iterrows():
                best = row.min()
                L.append(f"| {r} | " + " | ".join(("**%.2f**" if v == best else "%.2f") % v for v in row) + " |")
            L.append("")
    return L


def write_report(study, figures: dict, out=RESULTS_DIR) -> str:
    L = ["# Links, gauges and radar on three networks", "",
         "_Generated by `python src/run.py study`; every number below is computed._", "",
         "Per network, the 10 largest events of its study period (by radar domain-mean total), each "
         "mapped from every sensor on the same grid: the radar; the point gauges and every link "
         "method with the same IDW (power 2, 10 km). Hour-ending accumulations; scores only where "
         "both sides have a value; pooled over all cell-hours (maps) or station-hours (gauges) of a "
         "network's events. A map with gaps is scored on its share of the common sample, and its "
         "coverage is shown.", "", "## Findings", ""]
    L += [f"- {f}" for f in findings(study)] + [""]
    L += [f"![pooled scores]({figures['pooled']})", "",
          "## Retrieval x interpolation", "",
          "Every link retrieval (four power-law methods, and the RNN of `projects/cml_rnn` where "
          "a model is trained) mapped three ways: `idw` from each link's midpoint, `line` from "
          "virtual gauges along the path, `gmz` the same gauges corrected so each link keeps its "
          "own average (Goldshtein, Messer & Zinevich). Bold: the best interpolation per retrieval.", ""]
    L += grid_tables(study)
    for n in NAMES:
        m = study.pooled_maps[study.pooled_maps.network == n]
        if m.empty:
            continue
        L += [f"## {NAMES[n]}", ""]
        ev = study.events[study.events.network == n]
        L += [f"{len(ev)} events, {pd.Timestamp(ev.start.min()):%Y-%m-%d} to {pd.Timestamp(ev.end.max()):%Y-%m-%d}, "
              f"{ev.total_mm.sum():.0f} mm domain-mean in all.", ""]
        if n in figures.get("events", {}):
            L += [f"![largest event]({figures['events'][n]})", ""]
        for ref in ["radar"] + sorted(set(m.reference) - {"radar"}):
            sub = m[(m.reference == ref) & (m.cells != "all")].sort_values("nrmse")
            if sub.empty:
                continue
            L += [f"**Maps against the {ref} map** (cells <= 2 km of a link):", ""]
            L += _fmt_table(sub, ["estimate", "events", "coverage", "n", "rel_bias", "nrmse", "corr", "csi"]) + [""]
        for subset in ("gauges <= 5 km of a link", "all gauges"):
            p = study.pooled_points[(study.pooled_points.network == n) & (study.pooled_points.subset == subset)]
            if len(p):
                L += [f"**At the {CHECK_NAMES[CHECK_POINTS[n]]} gauges, {subset.replace('gauges ', '')}** "
                      "(hourly; the gauge map is rebuilt without the gauge being scored):", ""]
                L += _fmt_table(p.sort_values("nrmse"), ["estimate", "coverage", "n", "rel_bias", "nrmse", "corr"]) + [""]
    if study.errors:
        L += ["## Not scored", ""] + [f"- {k}: {v}" for k, v in study.errors.items()] + [""]
    L += ["## Files", "", "`events.csv`, `event_scores.csv` (per event, pair and cell set), "
          "`pooled_map_scores.csv`, `pooled_point_scores.csv`, `link_scores.csv` (each method's link "
          "totals against radar along the path and gauges near it).", ""]
    text = "\n".join(L)
    (out / "report.md").write_text(text)
    return text
