"""Paths and the study design."""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from core.geo import Domain
from core.opensense.fetch import DATA_ROOT

PROJECT_DIR = Path(__file__).resolve().parents[2]
RESULTS_DIR = PROJECT_DIR / "results"
FIGURES_DIR = RESULTS_DIR / "figures"
#: retrieved link rain, hourly link and gauge series, maps at the gauges (regenerated by run.py)
CACHE = DATA_ROOT / "_netherlands"

# Summer 2012: June-August, interval ends in (START, END]. The day before START is read
# too, as the 24 h the wet/dry classification and the reference level look back over.
START = pd.Timestamp("2012-06-01")
END = pd.Timestamp("2012-09-01")
SPINUP = pd.Timedelta("1D")

NL = Domain(50.75, 53.55, 3.35, 7.25, name="netherlands")
GRID_RES = 0.02                       # deg: ~1.4 km east-west, 2.2 km north-south
IDW = {"power": 2.0, "radius_m": 10_000.0}      # as maps/multisensor
WET_MM = 0.1                          # hourly total (mm) that counts as wet, maps and scores
P_CUT = 0.5                           # core.maps.wet_area default
MIN_COVERAGE = 0.75                   # an hour needs 3 of its 4 15-min steps
GAUGE_KM = 5.0                        # path-level: nearest KNMI gauge within this of the midpoint
MIN_KM = 1.0                          # path-level sensitivity row: paths at least this long
POL = "v"                             # not given; the operator says mostly vertical
